export const Routes = {
  me: '/me',
  page: '/page',
  website: '/website',
  tags: '/tags',
  pages: '/pages',
  eventsPageView: '/events/page_view',
  login: '/login',
  completeLogin: '/complete_login',
  logout: '/logout',
  subscribe: '/subscribe',
  unsubscribe: '/unsubscribe',
  completeSubscription: '/complete_subscription',
  updateMyAccount: '/update_my_account',
  deleteMyAccount: '/delete_my_account',
  verifyEmail: '/verify_email',
  placeOrder: '/place_order',
  completeOrder: '/complete_order',
  cancelorder: '/cancel_order',
  myOrders: '/my_orders',
  myProducts: '/my_products',
  product: '/product',
}
