ALTER TABLE pages ALTER COLUMN hash_blake3 SET NOT NULL;
ALTER TABLE snippets ALTER COLUMN hash_blake3 SET NOT NULL;
ALTER TABLE assets ALTER COLUMN hash_blake3 SET NOT NULL;
ALTER TABLE newsletters ALTER COLUMN hash_blake3 SET NOT NULL;
ALTER TABLE book_chapters ALTER COLUMN hash_blake3 SET NOT NULL;
ALTER TABLE product_pages ALTER COLUMN hash_blake3 SET NOT NULL;
